server:
  port: 8040

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customers?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: johnny
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#  redis:
#    host: 172.26.115.96
#    port: 6379
#    password: 123456
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: 100ms
  data:
    redis:
      host: localhost # Redis服务器地址
      port: 3278 # Redis服务器连接端口
#    password: # Redis服务器连接密码（默认为空）
      timeout: 500ms # 连接超时时间（毫秒）